# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.12"
   commands:
    - pip install '.[docs]' --find-links https://data.pyg.org/whl/torch-2.4.1%2Bcpu.html
    - sphinx-build docs/source/ $READTHEDOCS_OUTPUT/html/
