# Configuration for whole-graph embedding only (no patches)
experiment:
  name: "baseline_only_cora"
  description: "Whole graph embedding baseline without patches"
  output_dir: "results/baseline_only"

dataset:
  name: "Cora"

embedding:
  method: "gae"  # Non-variational GAE
  embedding_dim: 64  # Smaller embedding
  hidden_dim_multiplier: 2
  epochs: 500
  learning_rate: 0.01  # Higher learning rate
  patience: 15

patches:
  enabled: false  # Disable patching

visualization:
  create_individual_patches: false
  create_patch_grid: false
  umap_params:
    min_dist: 0.0
    metric: "euclidean"
  plot_params:
    pointsize: 8  # Larger points
    size: 2.5
    dpi: 800

output_files:
  whole_embedding: "cora_gae_baseline.png"