# Example configuration for Cora dataset embedding experiment
# Usage: python run/plot_embeddings.py configs/cora_example.yaml

experiment:
  name: "cora_l2g_vs_baseline"
  description: "Compare L2G patched embedding vs whole graph baseline on Cora"
  output_dir: "results/cora_experiment"

dataset:
  name: "Cora"  # Available: Cora, PubMed, CiteSeer, etc.
  # Optional dataset-specific parameters
  # data_root: "/tmp"  # Where to download/cache datasets
  # restrict_lcc: false  # Restrict to largest connected component
  # normalize_features: false

embedding:
  method: "vgae"  # Available: vgae, gae, dgi, graphsage
  embedding_dim: 128
  hidden_dim_multiplier: 2  # hidden_dim = embedding_dim * multiplier
  epochs: 10000
  learning_rate: 0.001
  patience: 20
  weight_decay: 0.0
  # Method-specific parameters
  variational: true  # For GAE/VGAE
  # dropout: 0.1  # For some methods

patches:
  enabled: true  # Set to false to only run whole graph embedding
  num_patches: 10
  clustering_method: "metis"  # Available: metis, louvain, fennel
  min_overlap: 256
  target_overlap: 512
  sparsify_method: "resistance"  # Available: resistance, rmst, none
  target_patch_degree: 4
  use_conductance_weighting: true
  verbose: false

alignment:
  method: "l2g"
  scale: false
  rotate: true
  translate: true

visualization:
  create_individual_patches: true
  create_patch_grid: true
  umap_params:
    min_dist: 0.0
    metric: "euclidean"
  plot_params:
    pointsize: 5
    size: 2.0
    dpi: 1200
    individual_patch_dpi: 600
    grid_dpi: 300

# Optional: Override default output filenames
output_files:
  patched_embedding: "patched_l2g_coords.png"
  whole_embedding: "whole_baseline_coords.png"
  patch_grid: "patch_grid_overview.png"
  # individual patches will be patch_01_embedding.png, etc.