# Deep Graph Infomax (DGI) experiment configuration
experiment:
  name: "cora_dgi_experiment"
  description: "Compare DGI patched vs whole graph on Cora"
  output_dir: "results/dgi_experiment"

dataset:
  name: "Cora"

embedding:
  method: "dgi"  # Deep Graph Infomax
  embedding_dim: 128
  hidden_dim_multiplier: 1  # DGI typically uses same hidden/embedding dim
  epochs: 1000
  learning_rate: 0.001
  patience: 20

patches:
  enabled: true
  num_patches: 8  # Fewer patches for DGI experiment
  clustering_method: "louvain"  # Different clustering method
  min_overlap: 128
  target_overlap: 256
  sparsify_method: "rmst"  # Random MST sparsification
  target_patch_degree: 5
  use_conductance_weighting: false  # Disable for this experiment
  verbose: false

alignment:
  method: "l2g"
  scale: true  # Enable scaling for DGI
  rotate: true
  translate: true

visualization:
  create_individual_patches: true
  create_patch_grid: true
  umap_params:
    min_dist: 0.3  # Different UMAP parameters
    metric: "cosine"  # Cosine distance for DGI
  plot_params:
    pointsize: 6
    size: 2.5
    dpi: 1000
    individual_patch_dpi: 400
    grid_dpi: 200

output_files:
  patched_embedding: "cora_dgi_patched.png"
  whole_embedding: "cora_dgi_baseline.png"