# PubMed dataset configuration - larger dataset example
experiment:
  name: "pubmed_l2g_comparison"
  description: "L2G embedding experiment on PubMed dataset"
  output_dir: "results/pubmed_experiment"

dataset:
  name: "PubMed"
  normalize_features: true  # Often helpful for PubMed

embedding:
  method: "vgae"
  embedding_dim: 128
  hidden_dim_multiplier: 4  # Larger hidden layer for PubMed
  epochs: 2000  # More epochs for larger dataset
  learning_rate: 0.001
  patience: 50  # More patience for larger dataset
  weight_decay: 1e-5

patches:
  enabled: true
  num_patches: 20  # More patches for larger dataset
  clustering_method: "metis"
  min_overlap: 512  # Larger overlaps for PubMed
  target_overlap: 1024
  sparsify_method: "resistance"
  target_patch_degree: 6  # Higher degree for denser dataset
  use_conductance_weighting: true
  verbose: true  # Enable verbose for large dataset

alignment:
  method: "l2g"
  scale: false
  rotate: true
  translate: true

visualization:
  create_individual_patches: true
  create_patch_grid: true
  umap_params:
    min_dist: 0.1  # Slightly different UMAP for PubMed
    metric: "euclidean"
  plot_params:
    pointsize: 3  # Smaller points for denser visualization
    size: 3.0     # Larger plot size
    dpi: 1200