# PubMed dataset with patched L2G embedding
experiment:
  name: "pubmed_patched_l2g"
  description: "PubMed dataset with patched L2G embedding"
  output_dir: "results/pubmed_patched"

dataset:
  name: "PubMed"
  normalize_features: true

embedding:
  method: "vgae"
  embedding_dim: 128
  hidden_dim_multiplier: 4
  epochs: 2000
  learning_rate: 0.001
  patience: 50
  weight_decay: 1e-5

patches:
  num_patches: 20
  clustering_method: "metis"
  min_overlap: 512
  target_overlap: 1024
  sparsify_method: "resistance"
  target_patch_degree: 6
  use_conductance_weighting: true
  verbose: true

alignment:
  method: "l2g"
  scale: false