# BTC-Reduced Simple Classification Configuration
# Simplified configuration for quick testing of Bitcoin entity classification

# Experiment metadata
experiment:
  name: "BTC_Reduced_Simple_Test"
  description: "Simple Bitcoin entity classification test (3 methods, 3 dimensions)"
  output_dir: "btc_simple_test_results"
  
# Dataset configuration
dataset:
  name: "btc-reduced"
  max_nodes: 5000  # Limit for faster testing
  
# Experimental parameters
parameters:
  dimensions: [32, 64, 128]  # Just 3 dimensions for quick test
  n_runs: 2  # Fewer runs for speed
  test_size: 0.2
  random_seed: 42
  
# Classification configuration
classification:
  classifier: "logistic_regression"
  params:
    max_iter: 1000
    solver: "lbfgs"
    random_state: 42
    multi_class: "ovr"
  preprocessing:
    scale_features: true
    class_weight: "balanced"

# Just 3 methods for quick comparison
methods:
  full_graph:
    enabled: true
    description: "VGAE on full BTC graph"
    base_embedding:
      method: "vgae"
      epochs: 100
      learning_rate: 0.001
      patience: 20
      verbose: false
  
  l2g_rademacher:
    enabled: true
    description: "Patched VGAE with L2G alignment"
    base_embedding:
      method: "vgae" 
      epochs: 100
      learning_rate: 0.001
      patience: 20
      verbose: false
    patches:
      num_patches: 8  # Fewer patches for smaller dataset
      clustering_method: "metis"
      min_overlap: 64
      target_overlap: 128
      sparsify_method: "resistance"
      target_patch_degree: 3
      use_conductance_weighting: true
    alignment:
      method: "l2g"
      randomized_method: "randomized"
      sketch_method: "rademacher"
  
  hierarchical_l2g:
    enabled: true
    description: "Hierarchical VGAE for BTC"
    base_embedding:
      method: "vgae"
      epochs: 100
      learning_rate: 0.001
      patience: 20
      verbose: false
    hierarchical:
      max_patch_size: 800
      min_overlap: 128  # Increased from 32 for sparse graph
      target_overlap: 256  # Increased from 64 for better connectivity

# Simple plotting
plotting:
  save_formats: ["png"]
  figure_size: [12, 8]
  dpi: 150
  
# Output configuration
output:
  save_raw_results: true
  save_summary: true
  save_plots: true
  save_report: false  # Skip detailed report for simple test

# Simple evaluation
evaluation:
  metrics: ["accuracy", "f1_score"]
  average_methods: ["weighted"]
  per_class_results: true