# Simple Configuration for Quick Testing
# Reduced parameters for faster experimentation

dataset:
  name: "Cora"
  use_default_splits: true
  split_seed: 42

embedding:
  method: "gae"  # Faster than VGAE for testing
  embedding_dim: 32  # Smaller dimension for speed
  hidden_dim: 16
  num_epochs: 50  # Fewer epochs for quick testing
  learning_rate: 0.01
  dropout: 0.5

patches:
  num_patches: 5  # Fewer patches for speed
  clustering_method: "metis"
  min_overlap: 15
  target_overlap: 30
  sparsification_method: "resistance"

alignment:
  method: "l2g"
  #num_epochs: 200  # Fewer epochs
  #learning_rate: 0.01
  #use_orthogonal_reg: true
  #orthogonal_reg_weight: 10
  #use_bfs_training: true
  #center_patches: false
  min_overlap: 15

node_reconstruction:
  loss_function: "mse"
  evaluation_metrics: ["mse", "mae"]
  reconstruction_method: "linear_decoder"

node_classification:
  classifier: "logistic_regression"
  evaluation_metrics: ["accuracy", "f1_macro"]
  stratify: true

hyperparameter_search:
  enabled: false

experiment:
  name: "cora_simple_test"
  random_seed: 42
  num_runs: 3  # Fewer runs for testing
  device: "auto"
  verbose: true
  save_intermediate: false  # Skip intermediate saves for speed
  output_dir: "experiments/results_simple"

logging:
  level: "INFO"
  log_to_file: true
  log_file: "experiments/logs/simple_test.log"

visualization:
  enabled: true
  methods: ["umap"]  # Only UMAP for speed
  save_plots: true
  plot_format: "png"