# Classification Configuration Template
# Specifies classifier, evaluation strategy, and preprocessing options

# Classifier configuration
classifier:
  type: "logistic_regression"  # Options: logistic_regression, random_forest, svm
  
  # Classifier-specific parameters
  params:
    # Logistic Regression parameters
    max_iter: 1000
    random_state: 42
    solver: "lbfgs"  # Options: newton-cg, lbfgs, liblinear, sag, saga
    multi_class: "auto"  # Options: auto, ovr, multinomial
    C: 1.0  # Regularization strength (inverse)
    
    # Random Forest parameters (if using RF)
    # n_estimators: 100
    # max_depth: null
    # min_samples_split: 2
    # min_samples_leaf: 1
    
    # SVM parameters (if using SVM)
    # kernel: "rbf"  # Options: linear, poly, rbf, sigmoid
    # gamma: "scale"  # Options: scale, auto, or float
    # probability: true  # Enable probability estimates

# Evaluation configuration
evaluation:
  # Data splitting
  test_size: 0.2  # Fraction for test set
  val_size: 0.1   # Fraction for validation set (from remaining data)
  stratify: true  # Maintain class distribution in splits
  random_state: 42
  
  # Cross-validation settings
  cross_validation:
    enabled: true  # Set to true to run k-fold CV
    folds: 5
    scoring: "accuracy"  # Options: accuracy, f1_macro, f1_weighted

# Preprocessing configuration  
preprocessing:
  scale_features: true  # Apply StandardScaler to features
  handle_imbalanced: false  # Apply class balancing (not implemented yet)
  
  # Feature selection (not implemented yet)
  # feature_selection:
  #   enabled: false
  #   method: "variance_threshold"
  #   params:
  #     threshold: 0.01