# Random Forest Classification Configuration
# Good for non-linear relationships and feature importance analysis

classifier:
  type: "random_forest"
  params:
    n_estimators: 100
    max_depth: null  # No limit on tree depth
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"  # sqrt(n_features)
    random_state: 42
    n_jobs: -1  # Use all CPU cores

evaluation:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  random_state: 42
  
  cross_validation:
    enabled: true
    folds: 5
    scoring: "f1_macro"

preprocessing:
  scale_features: false  # Random forests don't need feature scaling
  handle_imbalanced: false